### ISSUE TITLE
Running the quickstart command: gurobipy.GurobiError: License expired 2022-01-13

### ISSUE THREAD

**Issue by zhehaoli1999** [computational-imaging/ACORN#12]
Hi there, I have cloned the repo from zero and running the quickstart command:
``` 
conda env create -f environment.yml
# before proceeding, install Gurobi optimizer license (see above web link)
conda activate acorn 
cd inside_mesh
python setup.py build_ext --inplace
cd ../experiment_scripts
python train_img.py --config ./config_img/config_pluto_acorn_1k.ini
tensorboard --logdir=../logs --port=6006
```
But get error in `python train_image.py`:
```
Traceback (most recent call last):
  File "train_img.py", line 357, in <module>
    main()
  File "train_img.py", line 106, in main
    scale_init=opt.scale_init, max_patches=opt.max_patches)
  File "C:\Users\zheha\Research\Acorn\ACORN\dataio.py", line 265, in __init__
    self.quadtree = QuadTree(sidelength, patch_size)
  File "C:\Users\zheha\Research\Acorn\ACORN\data_structs.py", line 26, in __init__
    self.optim_model = gp.Model()
  File "src\gurobipy\env.pxi", line 67, in gurobipy.Env.__init__
  File "src\gurobipy\gurobi.pxi", line 32, in gurobipy.gurobi._getdefaultenv
  File "src\gurobipy\env.pxi", line 67, in gurobipy.Env.__init__
gurobipy.GurobiError: License expired 2022-01-13
```

**Comment by zhehaoli1999** [comment]
Updating Gurobi license from its offcial website https://portal.gurobi.com/iam/licenses/request/ fixes this problem.
